language: cpp
matrix:
  include:
# OSX
    - os: osx
      sudo: yes
      compiler: clang
      env: OPJ_CI_ARCH=x86_64 OPJ_CI_INSTRUCTION_SETS="-mavx2" OPJ_CI_BUILD_CONFIGURATION=Release OPJ_CI_INCLUDE_IF_DEPLOY=1
    - os: linux
      # "sudo: yes" and "dist: trusty" give us a worker with the AVX2 instruction set
      sudo: yes
      dist: trusty
      compiler: clang-3.8
      env: OPJ_CI_CC=clang-3.8 OPJ_CI_CXX=clang-3.8 OPJ_CI_INSTRUCTION_SETS="-mavx2" OPJ_CI_BUILD_CONFIGURATION=Release
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8
            - libssh2-1-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install libssh2; fi

before_script:
  - curl -u $TOKEN -o latest.json --silent https://api.github.com/repos/nim-lang/nightlies/releases/latest
  - export RELEASE=`cat latest.json | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'`
  - export TXZ=`cat latest.json | grep '"name":' | sed -E 's/.*"([^"]+)".*/\1/' | grep linux | tail -n 1`
  - export VERSION=`echo $TXZ | cut -d"-" -f 2,2`
  - echo "RELEASE = $RELEASE, TXZ = $TXZ, VERSION = $VERSION"
  - curl -L --silent -o $TXZ "https://github.com/nim-lang/nightlies/releases/download/$RELEASE/$TXZ"
  - tar xf $TXZ
  - cd nim-$VERSION
  - sh build.sh
  - bin/nim c koch
  - ./koch boot -d:release
  - ./koch nimble
  - export PATH=$(pwd)/bin:~/.nimble/bin:$PATH
  - cd ..

script:
  - nimble install -y
  - nimble test